## Explore diamonds dataset
You should notice that the diamonds data set will be listed as a 'Promise' in the workspace. This is a special object in R, and you need to run a command on the data to fully load the data set.  
Try running summary(diamonds)
```{r}
library(ggplot2)
?diamonds
data("diamonds")

dim(diamonds)
summary(diamonds)

str(diamonds)
table(diamonds$color)
```

## Price by cut
```{r}
# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).
ggplot(data=diamonds,
       aes(x=price))+
  geom_histogram(binwidth=800,fill='pink',color='grey')+
  facet_wrap(~cut,scales='free_y')+
  scale_x_continuous(breaks=seq(0,20000,10000))
# In the last exercise, we looked at the summary statistics
# for diamond price by cut. If we look at the output table, the
# the median and quartiles are reasonably close to each other.
by(diamonds$price,diamonds$cut,summary)
# This means the distributions should be somewhat similar,
# but the histograms we created don't show that.

# The 'Fair' and 'Good' diamonds appear to have 
# different distributions compared to the better
# cut diamonds. They seem somewhat uniform
# on the left with long tails on the right.
```
## Price per carat by cut

 