## Box Plots

+ [How to read and use a Boxplot](http://flowingdata.com/2008/02/15/how-to-read-and-use-a-box-and-whisker-plot/)
+ [interquartile range or IQR](https://en.wikipedia.org/wiki/Interquartile_range)
+ [Visualization of the IQR with a normal probability distribution function with ¦Ì=1 and ¦Ò=1 ](https://en.wikipedia.org/wiki/File:Boxplot_vs_PDF.svg)

```{r}
#histogram
qplot(x=friend_count,
      data=subset(pf,!is.na(gender)),
      binwidth=20)+
  scale_x_continuous(limits=c(0,1000),breaks=seq(0,1000,50))+
  facet_wrap(~gender)
```
## Box Plots
These boxes are hard to see as We have so many outliers. 
Each of these tiny little dot is an outlier in our data.
Outliers is those who are outside the range of one and half times the IQR from the media.
```{r}
by(pf$friend_count,pf$gender,summary)
```

```{r}
library(gridExtra)
#1
p1<-qplot(x=gender,y=friend_count,
      data=subset(pf,!is.na(gender)&friend_count<1000)
      ,geom='boxplot')
#2
p2<-qplot(x=gender,y=friend_count,
      data=subset(pf,!is.na(gender)),
      geom='boxplot')+
  scale_y_continuous(limits=c(0,1000))
#3
p3<-qplot(x=gender,y=friend_count,
      data=subset(pf,!is.na(gender)&friend_count<1000)
      ,geom='boxplot',
      ylim=c(0,1000)
      )
#4
p4<-qplot(x=gender,y=friend_count,
      data=subset(pf,!is.na(gender)),
      geom='boxplot')+
  coord_cartesian(ylim=c(0,250))

grid.arrange(p1,p2,p3,p4,ncol=2)
```

