## Transformed cartesian coordinate system
http://docs.ggplot2.org/current/coord_trans.html

## Usage
coord_trans(x = "identity", y = "identity", limx = NULL, limy = NULL, xtrans, ytrans)
## Arguments

+ *x, y*
transformers for x and y axes
+ *limx, limy*
limits for x and y axes. (Named so for backward compatibility)


```{r}
library(ggplot2)
data(diamonds)
names(diamonds)
```
# Three ways of doing transformation in ggplot:
```{r}
# The difference between transforming the scales and
# transforming the coordinate system is that scale
# transformation occurs BEFORE statistics(plot), and coordinate
# transformation afterwards.  
# Coordinate transformation also changes the shape of geoms:

#  * by transforming the data

d <- subset(diamonds, carat > 0.5)

p1<-ggplot(data=d,
       aes(x=log10(carat),y=log10(price)))+
  geom_point(alpha=1/20)+
  geom_smooth(method='lm')

#  * by transforming the scales
p2<-ggplot(data=d,
           aes(x=carat,y=price))+
  geom_point(alpha=1/20,size=2,shape=1)+
  geom_smooth(method='lm')+
  scale_x_log10()+
  scale_y_log10()
#  * by transforming the coordinate system
p3<-ggplot(data=d,
           aes(x=carat,y=price))+
  geom_point(alpha=1/20,size=2,shape=1)+
  coord_trans(x="log10",y="log10")+
  geom_smooth(method='lm')

p1
p2
p3
```
# Also works with discrete scales
```{r}
df <- data.frame(a = abs(rnorm(26)),letters)
ggplot(data=df,
       aes(a,letters))+
  geom_point()+
  coord_trans(x = "sqrt")

```

